# -*- coding: utf-8 -*-
"""AIR26_P01 - Python_Fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3VOcs45H9_uGzqZZJvGVJtsY_zdtmMp

# AIR26 Pre-Course Notebook 1  
# Python Fundamentals for AI and Robotics

**Audience:** Beginner B.Tech students  
**Course:** Artificial Intelligence and Robotics Summer School  
**Purpose:** This notebook will help you learn basic Python before starting Machine Learning, Computer Vision, ROS/ROS2, and Robotics coding.

---

## Estimated Time

This notebook may take approximately **2–3 hours** for beginner students.

You do not need to memorize everything. Focus on understanding the idea, running the code, observing the output, and completing the practice tasks.

---

## How to Use This Notebook

1. Open this notebook in **Google Colab** or **Jupyter Notebook**.
2. Run each code cell one by one.
3. In Google Colab, press **Shift + Enter** to run a cell.
4. Read the explanation before running the code.
5. Observe the output after running each cell.
6. Complete all **Try Yourself** and **Assignment** tasks.
7. Save your completed notebook for submission or discussion.

---

## Learning Outcomes

After completing this notebook, you will be able to:

1. Write and run simple Python programs.
2. Use variables, data types, operators, and conditions.
3. Use loops to repeat tasks.
4. Write simple functions.
5. Work with strings, lists, tuples, dictionaries, and sets.
6. Understand common Python errors and basic error handling.
7. Write a simple robot decision-making program.
"""



"""# 0. Why Python for AI and Robotics?

Python is widely used in AI and Robotics because it is simple, readable, and supported by many powerful libraries.

```text
Python → Data Handling → Machine Learning → Computer Vision → Robotics / ROS
```

Examples of Python usage:

| Area | Python Use |
|---|---|
| Machine Learning | Train models and make predictions |
| Computer Vision | Process images and detect objects |
| Robotics | Read sensors and control robot behavior |
| Data Analysis | Analyze sensor readings and experiment results |
| Automation | Write scripts to perform repeated tasks |

# 1. Your First Python Program

The `print()` function displays information on the screen.

In programming, we often begin with a simple message.
"""

# This is your first Python program.
# The print() function displays text on the screen.

print("Hello, AI and Robotics!")

"""## Comments in Python

Comments are notes written for humans. Python ignores comments during execution.

A comment starts with `#`.
"""

# This line is a comment. It will not be executed.

print("Comments help us understand code.")

"""# 2. Variables

A **variable** is a name used to store a value.

Think of a variable as a labeled box.

Example:

```text
battery_level = 85
```

Here, `battery_level` stores the value `85`.
"""

# Variables related to a simple robot

robot_name = "Mobile Robot"
battery_level = 85
speed = 0.5
obstacle_detected = True

print("Robot Name:", robot_name)
print("Battery Level:", battery_level, "%")
print("Speed:", speed, "m/s")
print("Obstacle Detected:", obstacle_detected)

"""## Good variable names

Use meaningful names.

Good examples:

```python
battery_level
robot_speed
obstacle_distance
```

Avoid unclear names:

```python
x
a1
data123
```

For beginners, readable code is more important than short code.

# 3. Basic Data Types

Python values have types.

| Data Type | Meaning | Example |
|---|---|---|
| `int` | Integer number | `10` |
| `float` | Decimal number | `0.75` |
| `str` | Text/String | `"Robot"` |
| `bool` | True/False value | `True` |
"""

# Checking data types using type()

robot_id = 101
obstacle_distance = 0.75
robot_mode = "autonomous"
is_moving = True

print(type(robot_id))
print(type(obstacle_distance))
print(type(robot_mode))
print(type(is_moving))

"""## Boolean Values in Robotics

A **Boolean** value has only two possible values:

```python
True
False
```

In robotics, Boolean values are very useful for decision-making.

Examples:

```text
sensor_active = True
obstacle_detected = False
battery_low = True
```
"""

# Boolean example in robotics
# Boolean values are either True or False.

sensor_active = True
obstacle_detected = False

print("Sensor Active:", sensor_active)
print("Obstacle Detected:", obstacle_detected)
print("Type of sensor_active:", type(sensor_active))
print("Type of obstacle_detected:", type(obstacle_detected))

"""# 4. Operators

Operators are used to perform operations on values.

## Arithmetic operators

| Operator | Meaning |
|---|---|
| `+` | Addition |
| `-` | Subtraction |
| `*` | Multiplication |
| `/` | Division |
| `//` | Integer division |
| `%` | Remainder |
| `**` | Power |
"""

# Simple arithmetic example

distance = 10       # meters
time = 5            # seconds

speed = distance / time

print("Speed =", speed, "m/s")

"""## Comparison operators

Comparison operators return either `True` or `False`.

| Operator | Meaning |
|---|---|
| `>` | Greater than |
| `<` | Less than |
| `>=` | Greater than or equal to |
| `<=` | Less than or equal to |
| `==` | Equal to |
| `!=` | Not equal to |
"""

# Robot safety example

obstacle_distance = 0.4   # meters

print("Is obstacle too close?")
print(obstacle_distance < 0.5)

"""## Logical operators

Logical operators combine conditions.

| Operator | Meaning |
|---|---|
| `and` | Both conditions must be true |
| `or` | At least one condition must be true |
| `not` | Reverses True/False |
"""

# A robot should move only if battery is sufficient and obstacle is not too close.

battery_level = 70
obstacle_distance = 1.2

can_move = battery_level > 20 and obstacle_distance > 0.5

print("Can the robot move?", can_move)

"""# 5. Type Conversion

Sometimes we need to convert one data type into another.

Common conversion functions:

| Function | Purpose |
|---|---|
| `int()` | Convert to integer |
| `float()` | Convert to decimal number |
| `str()` | Convert to string |
"""

# Type conversion example

distance_text = "1.25"          # This is a string
distance_value = float(distance_text)  # Convert string to float

print(distance_text, type(distance_text))
print(distance_value, type(distance_value))

"""## Note about `input()`

The `input()` function is useful for taking values from the user.

However, while learning in pre-course mode, we avoid interactive input in most cells so that all cells run smoothly.

Example for later use:

```python
name = input("Enter your name: ")
print("Hello", name)
```

## Important: Indentation in Python

Python uses **indentation** to define a block of code.

A block means a group of statements that belong together.

Correct indentation:

```python
if distance < 0.5:
    print("Stop the robot")
```

Incorrect indentation may cause an `IndentationError`.

For beginners, always remember:

```text
After if, elif, else, for, while, and def, the next line must be indented.
```

# 6. Conditional Statements

Conditional statements help a program make decisions.

```text
If condition is true → do something
Otherwise → do something else
```

Python uses `if`, `elif`, and `else`.
"""

# Robot obstacle decision

obstacle_distance = 0.4   # meters

if obstacle_distance < 0.5:
    print("Stop the robot")
else:
    print("Move forward")

# Multiple conditions using if-elif-else

battery_level = 15

if battery_level > 60:
    print("Battery is good")
elif battery_level > 20:
    print("Battery is medium")
else:
    print("Battery is low. Please charge the robot.")

"""## Try Yourself 1

Change the value of `obstacle_distance` and observe the output.

Suggested values:

```text
0.2, 0.5, 1.0
```
"""

# Try Yourself 1
# Change this value and run the cell.

obstacle_distance = 0.8

if obstacle_distance < 0.5:
    print("Stop the robot")
else:
    print("Move forward")

"""# 7. Loops

Loops are used to repeat a task.

Python commonly uses:

- `for` loop
- `while` loop

Loops are useful in robotics because sensors keep producing data repeatedly.
"""

# for loop example

sensor_readings = [0.9, 0.7, 0.4, 1.2]

for distance in sensor_readings:
    print("Obstacle distance:", distance, "m")

# Robot decision for each sensor reading

sensor_readings = [0.9, 0.7, 0.4, 1.2, 0.3]

for distance in sensor_readings:
    if distance < 0.5:
        print(distance, "m → Stop")
    else:
        print(distance, "m → Move")

# range() is used to generate a sequence of numbers.

for step in range(5):
    print("Robot step:", step)

"""## More about `range()`

The `range()` function can be used in three common ways:

```python
range(stop)
range(start, stop)
range(start, stop, step)
```

Important point:

```text
The stop value is not included.
```
"""

# range(start, stop)
# This prints robot step numbers from 1 to 5.
# Note: The stop value is not included.

for step in range(1, 6):
    print("Robot step:", step)

# range(start, stop, step)
# This prints even numbers from 0 to 8.

for value in range(0, 10, 2):
    print(value)

"""## Try Yourself 2: Robot Step Counter

Write a loop to print robot steps from 1 to 10.

Expected output:

```text
Robot step: 1
Robot step: 2
...
Robot step: 10
```
"""

# Try Yourself 2
# Complete and run this code.

for step in range(1, 11):
    print("Robot step:", step)

# while loop example
# The loop runs while the condition remains true.

battery_level = 5

while battery_level > 0:
    print("Robot running. Battery:", battery_level)
    battery_level = battery_level - 1

print("Battery empty. Robot stopped.")

"""## `break` and `continue`

- `break` stops the loop immediately.
- `continue` skips the current iteration and moves to the next one.
"""

# Stop checking once a dangerous obstacle is found.

sensor_readings = [1.0, 0.8, 0.6, 0.3, 0.9]

for distance in sensor_readings:
    if distance < 0.5:
        print("Dangerous obstacle found:", distance, "m")
        break
    print("Safe distance:", distance, "m")

"""# 8. Functions

A function is a reusable block of code.

Functions help us avoid repeating the same code again and again.

Basic structure:

```python
def function_name(parameters):
    statements
    return result
```

## Parameter vs Argument

A **parameter** is the variable written inside the function definition.

An **argument** is the actual value passed when calling the function.

Example:

```python
def decide_robot_action(distance):
    ...
```

Here, `distance` is a **parameter**.

```python
decide_robot_action(0.3)
```

Here, `0.3` is an **argument**.
"""

# Simple function example

def show_robot_name(name):
    print("Robot name is:", name)

show_robot_name("AIR Robot")

# Function to decide robot action

def decide_robot_action(distance):
    if distance < 0.5:
        return "Stop"
    else:
        return "Move forward"

print(decide_robot_action(0.3))
print(decide_robot_action(0.8))

# Function with two inputs

def check_robot_status(battery_level, obstacle_distance):
    if battery_level < 20:
        return "Charge battery"
    elif obstacle_distance < 0.5:
        return "Stop due to obstacle"
    else:
        return "Ready to move"

print(check_robot_status(80, 1.0))
print(check_robot_status(10, 1.0))
print(check_robot_status(80, 0.3))

"""## Optional: Recursion — For Curious Students

This topic is not required for the first Machine Learning sessions.

Read this section only after you are comfortable with functions.

Recursion means a function calls itself.

Beginners do not need to master recursion immediately, but it is useful to understand the idea.

Example: factorial

```text
factorial(5) = 5 × 4 × 3 × 2 × 1 = 120
```
"""

# Optional: Factorial using recursion

def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n - 1)

print(factorial(5))

"""# 9. Strings

A string is text written inside quotes.

Examples:

```python
"AI"
"Robot"
"Hello"
```
"""

robot_name = "AIR Mobile Robot"

print(robot_name)
print("Length:", len(robot_name))
print("Uppercase:", robot_name.upper())
print("Lowercase:", robot_name.lower())
print("First character:", robot_name[0])

# f-string is a clean way to create readable output.

robot_name = "Mobile Robot"
battery_level = 85

print(f"{robot_name} has {battery_level}% battery remaining.")

"""# 10. Lists

A list stores multiple values in one variable.

Lists are written using square brackets `[]`.

Lists are useful for storing sensor readings, student marks, robot positions, etc.
"""

# List of obstacle distances measured by a robot

distances = [0.9, 0.7, 0.4, 1.2, 0.3]

print(distances)
print("First reading:", distances[0])
print("Number of readings:", len(distances))
print("Minimum distance:", min(distances))
print("Maximum distance:", max(distances))

# Adding a new value to a list

distances = [0.9, 0.7, 0.4]
distances.append(1.1)

print(distances)

# Finding average manually

distances = [0.9, 0.7, 0.4, 1.2, 0.3]

average_distance = sum(distances) / len(distances)

print("Average distance:", average_distance)

"""## Try Yourself 3: Sensor Reading Analysis

Create a list of 5 obstacle-distance readings.

Find and print:

1. minimum distance,
2. maximum distance,
3. average distance.

Use meaningful variable names.
"""

# Try Yourself 3

obstacle_distances = [0.8, 0.6, 0.4, 1.2, 0.9]

minimum_distance = min(obstacle_distances)
maximum_distance = max(obstacle_distances)
average_distance = sum(obstacle_distances) / len(obstacle_distances)

print("Minimum distance:", minimum_distance)
print("Maximum distance:", maximum_distance)
print("Average distance:", average_distance)

"""# 11. Tuples

A tuple is similar to a list, but it cannot be changed after creation.

Tuples are written using parentheses `()`.

Use tuples when the data should remain fixed.
"""

# Robot position as a tuple: (x, y)

robot_position = (2, 3)

print("Robot position:", robot_position)
print("x-coordinate:", robot_position[0])
print("y-coordinate:", robot_position[1])

"""# 12. Dictionaries

A dictionary stores data in key-value pairs.

Dictionaries are useful when we want to store named information.
"""

# Robot status dictionary

robot_status = {
    "name": "Mobile Robot",
    "battery": 82,
    "mode": "autonomous",
    "speed": 0.5,
    "obstacle_detected": False
}

print(robot_status)
print("Robot mode:", robot_status["mode"])
print("Battery:", robot_status["battery"], "%")

# Updating dictionary values

robot_status = {
    "battery": 82,
    "mode": "manual"
}

robot_status["mode"] = "autonomous"
robot_status["battery"] = 75

print(robot_status)

"""## Reading All Values from a Dictionary

Sometimes we want to print all information stored in a dictionary.

For this, we can use `.items()`.
"""

# Dictionary iteration example

robot_status = {
    "battery": 82,
    "mode": "autonomous",
    "speed": 0.5,
    "obstacle_detected": False
}

for key, value in robot_status.items():
    print(key, ":", value)

"""# 13. Sets

A set stores unique values.

Sets are useful when duplicate values should be removed.
"""

# Sensor IDs may contain duplicate entries

sensor_ids = {"camera", "lidar", "imu", "camera", "gps"}

print(sensor_ids)

"""# 14. Common Errors and Debugging

Errors are normal in programming. A good programmer learns how to read and fix errors.

Common Python errors:

| Error | Common Reason |
|---|---|
| `SyntaxError` | Python grammar mistake |
| `NameError` | Variable name not defined |
| `TypeError` | Wrong data type used |
| `IndentationError` | Incorrect spacing |
| `ZeroDivisionError` | Dividing by zero |

Below we show corrected examples. The incorrect examples are shown as comments so that the notebook runs without stopping.
"""

# NameError example
# Incorrect:
# print(robot_speed)

# Correct:
robot_speed = 0.5
print(robot_speed)

# ZeroDivisionError example
# Incorrect:
# speed = distance / 0

# Correct:
distance = 10
time = 5
speed = distance / time
print(speed)

"""## Handling Errors Using `try-except`

Sometimes errors may occur during program execution.

Instead of stopping the whole program, we can handle errors using `try-except`.

This is useful in robotics because a robot program should handle unexpected situations safely.
"""

# Simple try-except example

distance = 10
time = 0

try:
    speed = distance / time
    print("Speed:", speed)
except ZeroDivisionError:
    print("Error: Time cannot be zero. Speed cannot be calculated.")

# Handling wrong type conversion

value = "robot"

try:
    number = int(value)
    print(number)
except ValueError:
    print("Error: This text cannot be converted into a number.")

"""## Optional: Simple File Writing and Reading

Robots often generate logs such as battery level, sensor readings, and status messages.

Python can write such information into a file and read it back later.

This topic is optional for the pre-course, but it is useful for robotics experiments.
"""

# Optional: Writing and reading a simple robot log file

log_message = "Robot status: Battery = 78%, Mode = autonomous"

# Write data to a text file
with open("robot_log.txt", "w") as file:
    file.write(log_message)

# Read data from the text file
with open("robot_log.txt", "r") as file:
    saved_message = file.read()

print(saved_message)

"""# 15. Mini Lab: Simple Robot Decision System

In this mini lab, we will combine:

- variables,
- lists,
- loops,
- conditions,
- functions,
- dictionaries.

Problem:

A robot receives obstacle-distance readings.  
For each reading:

- if distance is less than 0.5 m, the robot should stop,
- otherwise, the robot should move forward.
"""

# Mini Lab: Rule-based robot decision system

def decide_action(distance):
    if distance < 0.5:
        return "Stop"
    else:
        return "Move forward"

robot_status = {
    "name": "AIR Robot",
    "battery": 78,
    "mode": "autonomous"
}

sensor_readings = [1.2, 0.9, 0.45, 0.8, 0.3]

print("Robot:", robot_status["name"])
print("Mode:", robot_status["mode"])
print("Battery:", robot_status["battery"], "%")
print("-" * 40)

for reading in sensor_readings:
    action = decide_action(reading)
    print(f"Distance: {reading} m → Action: {action}")

"""# 16. Pre-Course Assignment

Complete these tasks before the summer school starts.

---

## Submission Instructions

Complete the following tasks in this notebook.

You may write your answers:

1. directly below each question, or  
2. in the **Assignment Practice Area** provided below.

Before submission:

- run all cells,
- check that there are no errors,
- save the notebook,
- submit the Colab link or `.ipynb` file as instructed by the coordinator.

Estimated assignment time: **45–60 minutes**.

---

## Task 1: Variables

Create variables for:

- robot name,
- battery level,
- robot speed,
- obstacle distance.

Print all values in meaningful sentences.

## Task 2: Decision Making

Write a program:

- if battery is below 20%, print `"Charge the robot"`,
- else if obstacle distance is below 0.5 m, print `"Stop"`,
- otherwise print `"Move forward"`.

## Task 3: List and Loop

Create a list of 5 sensor readings.  
For each reading, print whether it is safe or unsafe.

## Task 4: Function

Write a function named `robot_action(distance)` that returns `"Stop"` or `"Move forward"`.

## Task 5: Reflection

In 3–4 lines, write why Python is useful for AI and Robotics.
"""

# Assignment Practice Area
# Write your solutions below this line.
# You may add new code cells if required.

"""# Final Recap

In this notebook, you learned the Python fundamentals required for AI and Robotics.

## Key Concepts Covered

```text
Print Function
Variables
Data Types
Operators
Conditions
Loops
Functions
Strings
Lists
Tuples
Dictionaries
Sets
Basic Debugging
Error Handling
Simple File Logging
Robot Decision-Making
```

## Why This Matters for AI and Robotics

Python will help you to:

- process data,
- analyze sensor readings,
- write decision-making logic,
- prepare for Machine Learning coding,
- understand future robotics programming examples.

## Next Step

After completing this notebook, move to:

```text
Notebook 2: Python Libraries for AI and Robotics
```

There you will learn:

```text
NumPy → Matplotlib → Pandas → Basic Data Analysis
```
"""

robot_name="AURAX"
battery_level=100
robot_speed=0.8
obstacle_distance=54

print(f"Robot name is: {robot_name}\nBattery level is: {battery_level}%\nRobot speed is :{robot_speed}%\nObstacle distance is: {obstacle_distance}")

def robot_status(battery_level,obstacle_distance):
    if battery_level<20:
        print("Charge the robot")
    elif obstacle_distance<0.5:
        print("Stop")
    else:
        print("Move forward")
robot_status(20,10)

sensors=[23.4,34.5,5,65.4,34.8]
for sensor in sensors:
    if sensor<30:
        print(f"{sensor} is unsafe")
    else:
        print(f"{sensor} is safe")

def robot_action(distance):
  if distance<10:
    return "Stop"
  else:
    return "Move forward"
robot_action(30)

print("python is usefull in AI and roboyics because of its simple syntax and easier to understand and it has vast set of libraries")